# Generated by Django 2.2.4 on 2019-08-05 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_cabinet_with_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=100)),
                ('todo_text', models.TextField(blank=True, null=True)),
                ('dead_line', models.DateTimeField()),
                ('raise_date', models.DateTimeField(auto_now_add=True)),
                ('importance', models.IntegerField(null=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ('dead_line', 'raise_date'),
            },
        ),
    ]
