# Generated by Django 2.2.3 on 2019-08-02 06:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=100)),
                ('todo_text', models.TextField(blank=True, null=True)),
                ('dead_line', models.DateTimeField()),
                ('raise_date', models.DateTimeField(auto_now_add=True)),
                ('importance', models.IntegerField(null=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_cabinet.User')),
            ],
            options={
                'ordering': ('dead_line', 'raise_date'),
            },
        ),
    ]
